const API_BASE="http://localhost:8080/api";
const $=id=>document.getElementById(id);
const state={userId:localStorage.getItem("userId"),username:localStorage.getItem("username"),role:localStorage.getItem("role"),rooms:[]};
async function api(path,opts={}){const r=await fetch(API_BASE+path,{headers:{"Content-Type":"application/json"},...opts,body:opts.body?JSON.stringify(opts.body):undefined});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||d?.message||("HTTP "+r.status));return d}
function alertMsg(m){$("alert").textContent=m;setTimeout(()=>$("alert").textContent="",4000)}
function auth(){ $("loginBtn").textContent=state.userId?state.username:"Login";$("logoutBtn").hidden=!state.userId;$("adminBtn").hidden=state.role!=="ADMIN"}
function view(v){for(const id of ["roomsView","loginView","bookingsView","adminView"])$(id).hidden=id!==v+"View";if(v==="rooms")loadRooms();if(v==="bookings")loadBookings();if(v==="admin")loadAdmin()}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));
$("logoutBtn").onclick=()=>{localStorage.clear();location.reload()};
function roomCard(r){const d=document.createElement("article");d.className="room";d.innerHTML=`<span class="badge">${r.isAvailable?"Available":"Unavailable"}</span><h3>Room ${r.roomNumber} · ${r.roomType}</h3><p>${r.description||"Comfortable hotel room"}</p><p>₹${r.pricePerNight} / night · Capacity ${r.capacity??"-"}</p><button ${r.isAvailable?"":"disabled"}>Book</button>`;if(r.isAvailable)d.querySelector("button").onclick=()=>openBooking(r.id);return d}
async function loadRooms(){const box=$("rooms");box.innerHTML="Loading...";try{state.rooms=await api("/rooms");box.innerHTML="";const list=$("availableOnly").checked?state.rooms.filter(r=>r.isAvailable):state.rooms;list.forEach(r=>box.appendChild(roomCard(r)));if(!list.length)box.textContent="No rooms found."}catch(e){box.textContent=e.message}}
$("availableOnly").onchange=loadRooms;
function openBooking(id){if(!state.userId){alertMsg("Please login first.");return view("login")}$("roomId").value=id;$("checkIn").value="";$("checkOut").value="";$("bookingDialog").showModal()}
$("closeDialog").onclick=()=>$("bookingDialog").close();
$("bookingForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/bookings?userId="+state.userId,{method:"POST",body:{roomId:Number($("roomId").value),checkInDate:$("checkIn").value,checkOutDate:$("checkOut").value}});$("bookingDialog").close();alertMsg("Booking confirmed: "+d.confirmationCode);loadRooms()}catch(e){alertMsg(e.message)}};
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const d=await api("/auth/login",{method:"POST",body:{username:$("username").value,password:$("password").value}});Object.assign(state,{userId:String(d.userId),username:d.username,role:d.role});localStorage.setItem("userId",state.userId);localStorage.setItem("username",state.username);localStorage.setItem("role",state.role);auth();view("rooms");alertMsg("Login successful")}catch(e){alertMsg(e.message)}};
$("registerForm").onsubmit=async e=>{e.preventDefault();try{await api("/auth/register",{method:"POST",body:{firstName:$("firstName").value,lastName:$("lastName").value,username:$("regUsername").value,email:$("email").value,password:$("regPassword").value,phoneNumber:$("phone").value}});alertMsg("Registration successful. Please login.")}catch(e){alertMsg(e.message)}};
async function loadBookings(){const box=$("bookings");if(!state.userId)return box.textContent="Please login first.";try{const bs=await api("/bookings?userId="+state.userId);box.innerHTML=bs.length?bs.map(b=>`<article class="item"><b>${b.bookingStatus}</b> · ${b.confirmationCode}<br>Room ${b.room?.roomNumber||b.room?.id||"-"} · ${b.checkInDate} → ${b.checkOutDate}<br>₹${b.totalPrice||"-"} ${b.bookingStatus!=="CANCELLED"?`<button onclick="cancelBooking(${b.id})">Cancel</button>`:""}</article>`).join(""):"No bookings found."}catch(e){box.textContent=e.message}}
async function cancelBooking(id){try{await api("/bookings/"+id+"/cancel?userId="+state.userId,{method:"DELETE"});loadBookings();loadRooms()}catch(e){alertMsg(e.message)}}
async function loadAdmin(){if(state.role!=="ADMIN")return;const box=$("admin");try{const [users,rooms,bookings]=await Promise.all([api("/admin/users"),api("/rooms"),api("/bookings/all")]);box.innerHTML=`<h3>Users (${users.length})</h3><pre>${JSON.stringify(users,null,2)}</pre><h3>Rooms (${rooms.length})</h3><pre>${JSON.stringify(rooms,null,2)}</pre><h3>Bookings (${bookings.length})</h3><pre>${JSON.stringify(bookings,null,2)}</pre>`}catch(e){box.textContent=e.message}}
auth();view("rooms");