package com.hotelmanagement.service;
import com.hotelmanagement.dto.BookingDTO; import com.hotelmanagement.entity.Booking; import com.hotelmanagement.entity.Room; import com.hotelmanagement.entity.User; import com.hotelmanagement.repository.BookingRepository; import com.hotelmanagement.repository.RoomRepository; import com.hotelmanagement.repository.UserRepository; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.LocalDateTime; import java.time.temporal.ChronoUnit; import java.util.*;
@Service public class BookingService {
 @Autowired private BookingRepository bookingRepository; @Autowired private RoomRepository roomRepository; @Autowired private UserRepository userRepository;
 @Transactional public Map<String,Object> createBooking(Long userId,BookingDTO d){User u=userRepository.findById(userId).orElseThrow(()->new RuntimeException("User not found"));Room r=roomRepository.findById(d.getRoomId()).orElseThrow(()->new RuntimeException("Room not found"));if(!r.getIsAvailable())throw new RuntimeException("Room is not available");long days=ChronoUnit.DAYS.between(d.getCheckInDate(),d.getCheckOutDate());if(days<=0)throw new RuntimeException("Invalid booking dates");BigDecimal total=r.getPricePerNight().multiply(BigDecimal.valueOf(days));String code=UUID.randomUUID().toString().substring(0,8).toUpperCase();Booking b=new Booking();b.setUser(u);b.setRoom(r);b.setCheckInDate(d.getCheckInDate());b.setCheckOutDate(d.getCheckOutDate());b.setTotalPrice(total);b.setBookingStatus("CONFIRMED");b.setConfirmationCode(code);b.setCreatedAt(LocalDateTime.now());b=bookingRepository.saveAndFlush(b);r.setIsAvailable(false);roomRepository.saveAndFlush(r);Map<String,Object> result=new HashMap<>();result.put("id",b.getId());result.put("confirmationCode",code);result.put("bookingStatus","CONFIRMED");result.put("checkInDate",d.getCheckInDate().toString());result.put("checkOutDate",d.getCheckOutDate().toString());result.put("totalPrice",total.doubleValue());return result;}
 public List<Booking> getUserBookings(Long id){return bookingRepository.findByUserId(id);} public Booking getBookingById(Long id){return bookingRepository.findById(id).orElseThrow(()->new RuntimeException("Booking not found"));} public List<Booking> getAllBookings(){return bookingRepository.findAll();}
 @Transactional public void cancelBooking(Long bookingId,Long userId){Booking b=getBookingById(bookingId);if(!b.getUser().getId().equals(userId))throw new RuntimeException("Unauthorized: You can only cancel your own bookings");if("CANCELLED".equals(b.getBookingStatus()))throw new RuntimeException("Booking is already cancelled");b.setBookingStatus("CANCELLED");bookingRepository.saveAndFlush(b);Room r=b.getRoom();r.setIsAvailable(true);roomRepository.saveAndFlush(r);}
 @Transactional public Booking cancelBooking(Long id){Booking b=getBookingById(id);b.setBookingStatus("CANCELLED");Room r=b.getRoom();r.setIsAvailable(true);roomRepository.save(r);return bookingRepository.save(b);}
 public Booking getBookingByConfirmationCode(String c){return bookingRepository.findByConfirmationCode(c).orElseThrow(()->new RuntimeException("Booking not found"));}
}